apiVersion: cache.example.com/v1alpha1
kind: CronJob
metadata:
  name: hello-crd
spec:
  schedule: "*/1 * * * *"
  scheduledJobsLimits: 4
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure