apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjob-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cronjob-operator
  template:
    metadata:
      labels:
        name: cronjob-operator
    spec:
      serviceAccountName: cronjob-operator
      containers:
        - name: cronjob-operator
          # Replace this with the built image name
          image: hub.geovis.io/zhangjx/cronjobs:v0.1 
          command:
          - cronjob-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cronjob-operator"
      nodeSelector:
        kubernetes.io/hostname: t33
